#  Database Configuration
redis:
  host: "127.0.0.1"
  port: 6379
  authentication:
    enabled: false
    password: ""

#  url: "redis://localhost:6379"
mongodb:
  url: "mongodb://localhost:27017/SGSoftware?retryWrites=true&w=majority"
  database: "SGSoftware"
