name: Lemon
version: ${git.commit.id.abbrev}
main: com.solexgames.lemon.Lemon

author: SolexGames
website: https://solexgames.com
description: Extensive rank, punishment, & moderation suite.

depend: [Cubed, spark]
