name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean shadowJar
      - name: Transfer to local Spigot deployment folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BAR_HOST_1 }}
          username: root
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          source: ./bukkit/build/libs/Lemon.jar
          target: /root/home/pvpbar/downloader
      - name: Transfer the jar to the root directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BAR_HOST_1 }}
          username: root
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            mv /root/home/pvpbar/downloader/bukkit/build/libs/Lemon.jar /root/home/pvpbar/downloader
            rm -rf /root/home/pvpbar/downloader/bukkit/build/libs
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
